///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxAgent
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxAgentRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("adca8137-7128-4c6a-94ee-9bd646130516")]
    public partial class RxAgentRepository : RepoGenBaseFolder
    {
        static RxAgentRepository instance = new RxAgentRepository();

        /// <summary>
        /// Gets the singleton class instance representing the RxAgentRepository element repository.
        /// </summary>
        [RepositoryFolder("adca8137-7128-4c6a-94ee-9bd646130516")]
        public static RxAgentRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxAgentRepository() 
            : base("RxAgentRepository", "/", null, 0, false, "adca8137-7128-4c6a-94ee-9bd646130516", ".\\RepositoryImages\\RxAgentRepositoryadca8137.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("adca8137-7128-4c6a-94ee-9bd646130516")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class RxAgentRepositoryFolders
    {
    }
#pragma warning restore 0436
}